# Generated by Django 4.2.6 on 2023-10-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_course', models.CharField(max_length=100, verbose_name='Название курса')),
                ('preview_course', models.ImageField(blank=True, null=True, upload_to='course_previews/', verbose_name='Картинка')),
                ('description_course', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_lesson', models.CharField(max_length=100, verbose_name='Название урока')),
                ('description_lesson', models.TextField(verbose_name='Описание урока')),
                ('preview_lesson', models.ImageField(blank=True, null=True, upload_to='lesson_previews/', verbose_name='Картинка курса')),
                ('video_link', models.URLField(verbose_name='Ссылка на урок')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
