# Generated by Django 4.2.6 on 2023-10-30 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countlesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_lesson', models.PositiveIntegerField(verbose_name='Количество уроков')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'количество уроков',
                'verbose_name_plural': 'Количество уроков',
            },
        ),
    ]
